### ISSUE TITLE
A couple shortcuts for the peewee example

### ISSUE THREAD

**Issue by coleifer** [sloria/PythonORMSleepy#1]
Nice project!  Thanks for including peewee :) . Just wanted to point you to a couple shortcuts you could use in the peewee example.

`flask_peewee.utils.get_object_or_404` could replace the `try/except` blocks:

``` python
    def get(self, id):
        '''Get an item.'''
        item = get_object_or_404(Item, Item.id == id)
        return jsonify(ItemSerializer(item).data)
```

It looks like marshmallow iterates over the query, so you can pass it directly to the serializer:

``` python
    def index(self):
        '''Get all people, ordered by creation date.'''
        query = Person.select().order_by(Person.created.desc())
        data = PersonSerializer(query, exclude=('created',)).data
        return jsonify({"people": data})
```

**Comment by sloria** [comment]
Thanks for writing an excellent ORM!

I didn't use `get_object_or_404` originally because I wanted to show the syntax for getting an object using "vanilla" peewee.

However, one of the goals of this project is to demonstrate each ORM's integration with Flask, so I've added examples using both styles for getting a single record.

Re: serializing a query: I just fixed a bug in marshmallow that wouldn't allow a serializer to be passed a Peewee query (previously, it worked with a Person query but not with an Item query). The example has been updated. Thanks for the suggestion.

**Comment by coleifer** [comment]
> I didn't use get_object_or_404 originally because I wanted to show the syntax for getting an object using "vanilla" peewee.

Awesome, I guessed that but just wanted to be sure.

> (previously, it worked with a Person query but not with an Item query)

Interesting!  Glad it's working now.  Again, thanks for your project and for including peewee.
